### ISSUE TITLE
Basic Puzzle Control UI

### ISSUE THREAD

**Issue by MrLever** [cop4934-fall19-group32/Project-32#35]
The puzzle scene of our hello world example needs to allow the following:

- [ ] Player can see all their available instructions (Input, Output)
- [ ] Player can drag their instructions into the solution window
- [ ] Player can hit a play button run their solution
- [ ] Player can hit a stop button to stop running their solution and reset

**Comment by MrLever** [comment]
@SSimonian I recommend breaking this into sub-issues

**Comment by MrLever** [comment]
OBE
